export default {
	id: 1002,
	langCode: "ch",
	langName: "Bing chilling",
	langFlag: "🇨🇳",
	langText: "语言设置为中文。",
	langNotFound: "未找到语言。",
	langCurrent: "当前语言。中文。",

	invalidName: "无效的名称。该名称不能包含空格或特殊字符。",
	invalidFormatSrv: "无效的格式。使用: '<address>|<query_port>|<ts3_port>'",
	invalidFormatAcc: "无效的格式。使用: '<query_user>|<query_passwd>'",
	noInstSelected: "没有选择服务器。",
	notLinked: "没有服务器链接到这个组。",
	notAllowed: "你不允许这样做。",
	useInGroup: "在一个有链接服务器的组中使用这个命令。",
	errorPrefix: "意外的错误。",
	botDisconnected: "机器人被断开连接了。",
	channelLeave: "离开机器人频道。",
	channelJoin: "进入机器人频道。",
	channelSwitch: "切换到频道: ",
	notConnected: "错误。机器人没有连接。",
	用户在线: " 用户: ",
	connectError: "在<attempts>尝试后无法连接。最后一个错误。",
	replyError: "无法执行命令。",

	optionOn: "开",
	optionOff: "关闭",

	stateIdle: "闲置状态",
	stateConnecting: "正在连接",
	stateConnected: "已连接",
	stateError: "断开连接（错误）",

	availableDev: "供开发者使用",
	availableChat: "仅适用于用户",
	availableGroup: "仅适用于组",
	availableAll: "适用于用户和组",

	groupJoin: "加入了该组。",
	groupLeave: "离开该组。",

	spamStart1: "触发了垃圾邮件保护。你的信息将被忽略。<time>分钟。",
	spamStart2: "垃圾邮件保护被触发。由于机器人无法与你私下联系，你在这里收到这个信息: 你的信息将被忽略。<time>分钟。",
	spamEnd: "你不再因为垃圾邮件而被忽略。下次你将被忽略。<time>分钟。",

	spamIgnoreTrigger: "垃圾邮件保护被触发。你的信息将被忽略，时间为。",
	spamIgnoreRevoke: "您不再因垃圾邮件而被忽略。下次你将被忽略，因为。",
	spamTimeUnit: " 分钟。",
	noAgreement: "在添加服务器之前，请阅读并同意服务条款（使用/tos）。",
	addInfo: "你将需要以下信息: <code>\r\n- 服务器地址\r\n- 查询端口\r\n- vserver ID\r\n- 一个查询账户</code>\r\n开始时，告诉我你想怎么称呼这个服务器（例如: Jeff）",
	addLimit: "对不起，你已经达到了每个用户5个服务器的限制。你可以随时/删除或更改不需要的，但如果你真的需要更多，请用/devmessage联系我",
	linkLimit: "对不起，但你已经达到了每个用户20个链接组的限制。你可以随时/取消链接或编辑不需要的，但如果你真的需要更多，用/devmessage联系我",
	admin4allOn: "现在每个人都是管理员......你都做了什么？",
	admin4allOff: "撤销了管理员的权限。",
	availableCommands: "可用的命令: ",
	groupNotLinked: '这个组没有与TS3服务器相连。\r\n在机器人聊天中使用 <code>/add</code> 或 <code>/link</code>。 <a href="https://t.me/ts3bot?start">Click me</a>。',
	conConnect: "正在连接。这有时可能需要一些时间...",
	conConnecting: "机器人仍然在连接。要取消，请使用/disconnect",
	conConnected: "机器人仍在连接。使用/reconnect代替。",
	delConfirm: "删除一个服务器将解除所有相关组的链接，如果你确定，请准确输入以下内容: \r\n\r\n",
	delConfirmStr: "是的，删除",
	devWait: "在发送另一条信息之前，你必须等待一个答案。",
	devSend: "好吧:)告诉我你想要什么。",
	disconnect: "断开连接...",
	faqText:
		"TS3Bot FAQ:\r\n你可以通过连接到你的TS3服务器来创建一个查询账户，然后点击'工具栏>附加功能>服务器查询登录'并输入一个名称。" +
		"机器人需要以下TS3权限才能正常工作: \r\n" +
		" - b_virtualserver_info_view\n - b_virtualserver_connectioninfo_view\n - b_virtualserver_channel_list\r\n" +
		"-b_virtualserver_client_list\n -b_virtualserver_notify_register\n -b_virtualserver_notify_unregister\n" +
		"用户名和频道信息每2分钟才更新一次。" +
		"这个机器人是用nodejs编写的。" +
		"代码行数。<sloc>",
	helpText:
		"TS3Bot帮助: \r\n这个机器人提供了一个接口，用于连接TeamSpeak 3服务器" +
		"到Telegram（特定的群组），以便交叉聊天和看到在线用户。" +
		"使用官方查询API，因此需要一个账户。在使用机器人之前，请接受/tos。你可以用以下方式添加一个新的服务器。/add\r\n" +
		" 菜单应该可以指导你，但如果你遇到错误，你应该阅读/faq，在紧急情况下，请使用/devmessage联系我",
	tosText:
		"TS3Bot TOS (Terms of Service):\r\n这个机器人的目的是作为一个有趣的教育项目，由我和为我" +
		"并且我不对它可能对你或任何其他方造成的任何损害负责。由于这是一项免费的服务， 不保证它能在短时间内完成。" +
		"不保证它能一直在线或运行。禁止你篡改机器人和相关的 系统。" +
		"系统进行压力、性能或安全测试。这些事情可能被认为是DDoS，并将被主机商起诉" +
		" 存储的数据使用RSA128加密，只用于在重新启动之间保存数据。",
	tosAgree: "要同意，请准确键入。'<tos_string>'",
	tosString: "我同意",
	ignorebots: "其他TS3查询客户端将被忽略",
	unignorebots: "其他TS3查询客户端不会被忽略。",
	addLink: "现在请告诉我新链接的名称。",
	accountSet: "账户细节设置。",
	accBotName: " 接下来告诉我你服务器上的机器人的名字。",
	channelSet: "频道名称设置。",
	channelComplete: " 设置已经完成。你现在可以:\r\n/将服务器连接到一个组:\r\n/连接机器人:\r\n或编辑设置（见/command）",
	channelNameErr: "错误。名称需要在2到32个字符之间。",
	tosAccept: "Thanks :)",
	tosReject: ":(",
	addedServer: "服务器已创建。现在告诉我服务器地址，格式如下: \r\n'<ip_or_host>|<query_port>|<ts3_vserver_id>",
	nameInUse: "这个名字已经在使用了。",
	linkDestroyed: "深层链接 '<link>' 被破坏。",
	linkingDestroyed: "群组链接 '<linking>' 被破坏。",
	serverUnlinked: "服务器被从这个组中取消链接。",
	serverDeleted: "服务器被删除。",
	deleteError: "错误。输入是区分大小写的。重试或/取消",
	devSent: "信息已经送达。我将研究它并尝试与你联系",
	devError: "请使用10到500个字符之间。当前: ",
	linkGroup: "好的，现在可以使用这个链接将机器人添加到一个组中: ",
	nameError: "名称不能包含空格或特殊字符。",
	serverSelected: "选择了服务器。",
	serverNotFound: "服务器不存在。",
	setName: "机器人名称设置。",
	setNameFirst: " 现在请告诉我机器人应该加入的频道的确切名称。",
	setServer: "服务器地址设置。",
	setServerFirst: " 现在请告诉我账户的详细信息，格式如下:\r\n'<query_user>|<query_password>'。",
	linkingNotFound: "链接不存在。",
	groupAlreadyLinked: "这个组已经被链接到一个服务器上了。",
	groupLinked: "TS3服务器被成功链接到这个组",
	invalidLink: "错误: 深度链接密钥无效。",
	startChat: "嗨！这个机器人可以将你的TeamSpeak3服务器链接到一个或多个Telegram群组",
	spamCheck: "垃圾邮件检查设置为。",
	silentMode: "无声模式设置为。",
	serverNameHidden: "服务器名称将在Telegram中隐藏。",
	serverNameShown: "服务器名称将在Telegram中显示。",
	groupNameHidden: "群组名称将在TeamSpeak中隐藏",
	groupNameShown: "群组名称将在TeamSpeak中隐藏。",
	shareMediaOn: "共享小组媒体将在TS3中可用。",
	shareMediaOff: "共享的群组媒体在TS3中不可用。",
	用法: "用法。",
	setServerAddress: "好的，请告诉我服务器地址，格式为'<address>|<query_port>|<ts3_vserver_id>'。",
	setBotName: "好的，请告诉我机器人在你的服务器上应该如何称呼自己。",
	setChatMode: "聊天模式设置为。",
	setChannelDepth: "频道深度设置为。",
	setChannelName: "好的，请告诉我机器人应该加入的频道名称。",
	setAccountDetails: "好的，请告诉我格式为'<query_user>|<query_passwd>'的账户细节",
	选择服务器: "点击或写下你想编辑/选择的服务器的名称。",
	serverReconnecting: "重新连接......这有时可能需要一些时间（关于错误请看私人聊天）",
	setMoveNotifications: "客户端移动通知设置为。",
	setJoinNotifications: "客户加入通知设置为。",
	manageHeader: "具有链接组的服务器: <代码>",
	manageSelected: "（选定）",
	manageFooter: "/unlink [link_name] to delete.",
	enableAutoConnect: "机器人将自动（重新）连接。",
	disableAutoConnect: "机器人不会自动（重新）连接。",
	noUsersOnline: "没有用户在线。",
	autoConnecting: "正在自动连接。请稍等...",
	leftServer: "离开了服务器。",
	joinedServer: "加入了服务器。",
	botConnected: "</b>现在已经连接了。<b><users>用户</b>和<b><bots>机器人</b>在线。",
	botChannelMsg: "",
	LiveTreeFormat: "LiveTree\r\n<code><tree></code>\r\nChanged: <time>",
	liveTreeError: " ⚠️",
	liveTreeStop: "LiveTree 被停止并删除。",

	menu00: "TS3Bot menu:",
	menu01: "\r\nGroup is linked.",
	menu02: "\r\nGroup is not linked.",
	menu03: "\r\nYour servers:     ",
	menu04: "\r\nYour linkings:    ",
	menu05: "\r\nSelected server:  ",
	menu06: "\r\nNo Server selected.",

	info00: "Group & Server Info:  ",
	info01: "\r\nowner:            ",
	info02: "\r\nchanneldepth:     ",
	info03: "\r\nother groups:     ",

	info10: "Selected Server Info: ",
	info11: "\r\nlabel:            ",
	info12: "\r\nlinked groups:    ",

	info20: "\r\nstatus:           ",
	info21: "\r\nserver name:      ",
	info22: "\r\nplatform:         ",
	info23: "\r\nversion:          ",
	info24: "\r\nuser:             ",
	info25: "\r\nchannel:          ",

	settings00: "Group & Server Settings:",
	settings01: "\r\nadmin 4 all:  ",
	settings02: "\r\nchat mode:    ",
	settings03: "\r\nshare media:  ",
	settings04: "\r\nshow group:   ",
	settings05: "\r\nshow server:  ",
	settings06: "\r\nignore bots:  ",
	settings07: "\r\nsilent:       ",
	settings08: "\r\nspam check:   ",
	settings09: "\r\nnotify join:  ",
	settings10: "\r\nnotify move:  ",

	settings20: "Selected Server Settings:",
	settings21: "\r\nlabel:          ",
	settings22: "\r\nserver address: ",
	settings23: "\r\nquery port:     ",
	settings24: "\r\nserver port:    ",
	settings25: "\r\nquery user:     ",
	settings26: "\r\nquery pass:     ",
	settings27: "\r\nclient name:    ",
	settings28: "\r\nchannel name:   ",
	settings29: "\r\nchanneldepth:   ",
	settings30: "\r\nauto connect:   ",

	stats01: "\r\nlast restart:      ",
	stats02: "\r\nreceived messages: ",
	stats03: "\r\nknown users:       ",
	stats04: "\r\nknown groups:      ",
	stats05: "\r\ninstances:         ",
	stats06: "\r\nlinked groups:     ",
	stats07: "\r\nglobal ts3 users:  ",
	stats08: "\r\nTS3bot ram usage:  ",

	actionCommand: "无效响应（命令不允许）",
	actionCancel: "行动取消了。",
	actionNoCancel: "没有什么可以取消的¯\\_(ツ)_/¯",

	pmDisabled: "PM禁用。",
	pmEnabled: "启用PM。(测试功能！)",

	commandsGroup: "* = 需要管理权限/r\n# = 需要链接的服务器/r\n",
	commandsChat: "~ = 需要选择的服务器/r\n",
	commandForbidden: "你不允许使用这个命令",
	commandNotLinked: "没有服务器链接到这个组。/添加一个服务器并/链接它。",
	commandErrChat1: '这个命令只适用于<a href="https://t.me/ts3bot?start">机器人聊天</a>',
	commandErrChat2: "这个命令只适用于群聊。使用/链接。",
	commandNoSelect: "请先/选择一个服务器。",
	commandNoAdded: "请先/添加一个服务器。",
	commandNoTOS: "请先接受/tos和/添加一个服务器",
	commandResult: "命令搜索匹配'<command>': ",
	commandNotFound: "没有找到与'<command>'匹配的命令。",
	commandCommand: "\r\n<code>Command:      [用法]\r\nDescription:  [desc]\r\nAvailable:    [available]</code>",
	commandsDetail: "\r\nFor details enter: <code>/commands [command_name]</code>",
	commandMax: "最多可显示5个条目",

	cmd_addServer: "添加服务器",
	cmd_admin4all: "admin 4 all",
	cmd_cancel: "取消行动",
	cmd_commands: "所有命令",
	cmd_connect: "连接",
	cmd_debug: "调试设置",
	cmd_delete: "删除服务器和链接",
	cmd_devmessage: "开发者信息",
	cmd_disconnect: "断开连接",
	cmd_faq: "FAQ",
	cmd_help: "帮助",
	cmd_ignorebots: "忽略其他机器人",
	cmd_lang: "🇺🇸 / 🇩🇪",
	cmd_link: "链接到一个组",
	cmd_livetree: "服务器实时视图",
	cmd_manage: "管理",
	cmd_menu: "菜单",
	cmd_notifyjoin: "在TS3加入时通知",
	cmd_pm: "私人信息",
	cmd_reconnect: "重新连接",
	cmd_sample: "样本",
	cmd_select: "选择一个服务器",
	cmd_setaccount: "查询账户详情",
	cmd_setchannel: "TS3通道名称",
	cmd_setchanneldepth: "频道输出深度",
	cmd_setchatmode: "TS3聊天模式",
	cmd_setname: "TS3显示名称",
	cmd_setserver: "TS3服务器地址",
	cmd_settings: "设置",
	cmd_showgroup: "在TS3中显示组名？",
	cmd_showserver: "在Telegram中显示服务器名称？",
	cmd_silent: "沉默的信息？",
	cmd_spamcheck: "垃圾邮件检查",
	cmd_start: "开始",
	cmd_stats: "Stats",
	cmd_susers: "简短的用户列表",
	cmd_tos: "服务条款",
	cmd_unlink: "从一个组中取消服务器的链接",
	cmd_users: "用户列表",

	cmd_whinfo: "Webhook 信息",
	cmd_reload: "重新加载模块和语言",
	cmd_rstdev: "重置一个用户的dev-msg-sent-status",
	cmd_loaddata: "加载数据",
	cmd_savedata: "存储数据",
	cmd_lol: "idk",
};
