version: '2'
services:
    node_ts3bot:
        build: .
        container_name: node_ts3bot
        hostname: node_ts3bot
        image: debian/latest
        restart: unless-stopped
        ports:
            - 80:80 # can be removed if not using webhook
            - 8080:8080 # can be removed if not using fileProxy
        env_file:
            - bot-variables.env # all possible environment variables (change BOT_TOKEN !)
        volumes:
            - ./data:/app/data # bot settings storage directory